
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<path>.*), /$\{path}
        - id: project-service
          uri: lb://project-service
          predicates:
            - Path=/project/**
          filters:
            - RewritePath=/project/(?<path>.*), /$\{path}
        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/task/**
          filters:
            - RewritePath=/task/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://host.docker.internal:9411

server:
  port: 8762

eureka:
  instance:
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/


management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"
  context-path: http://localhost:${server.port}/actuator


info:
  application:
    name: ${spring.application.name}
    description: Ticketing Application
    version: '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: '@project.parent.version@'

