spring:
  application:
    name: ticketing-project-rest
  profiles:
    active: default

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/ticketing-app
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
server:
  port: 9092
