spring:
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://host.docker.internal:9411
  application:
    name: project-service
  profiles:
    active: default

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/ticketing-app
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
server:
  port: 9091

eureka:
  instance:
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/


management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"
  context-path: http://localhost:${server.port}/actuator


info:
  application:
    name: ${spring.application.name}
    description: Ticketing Application
    version: '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: '@project.parent.version@'

resilience4j:
  circuitbreaker:
    configs:
      default:
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 2
        waitDurationInOpenState: 10000
        slidingWindowType: COUNT_BASED
    instances:
      user-service:
        baseConfig: default
        waitDurationInOpenState: 15000
      task-service:
        baseConfig: default
        waitDurationInOpenState: 20000
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 200
    instances:
      user-service:
        baseConfig: default
  ratelimiter:
    instances:
      test:
        timeout-duration: 5000
        limitRefreshPeriod: 5000
        limitForPeriod: 1